#FROM python:2.7-alpine
#FROM python:2-alpine
FROM alpine:3.7
RUN apk add --update python python-dev py-pip build-base g++
WORKDIR /app
COPY requirements.txt /app/
#RUN apk add make automake gcc g++ subversion python2-dev
#RUN pip install --upgrade pip
RUN pip install -r requirements.txt
#CMD ["python", "app.py"]

